name: Test
on: push
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run test_main.py
        run: python -u src_old/test_*.py
  evaluation_score:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run
        run: |
          score=$(python -u src/use_dataset.py)
          echo "score=$score" >> $GITHUB_OUTPUT

      - name: show average score
        run: echo "${{ steps.run.outputs.score }}"